[workspace]
resolver = "2"
members = [
    "crates/ps-core",
    "crates/ps-factory",
    "apps/ps-cli",
    # "apps/ps-gui",
    "apps/ps-runner",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
